[package]
name = "danmu2ass"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.56"
xml-rs = "0.8.4"
float-ord = "0.3.2"
clap = { version = "3.1.6", features = ["derive"] }
log = "0.4.15"
pretty_env_logger = "0.4.0"
