# 在本文件存在时，优先读取本文件的内容，不会读取命令行参数

# 需要转换的 XML 文件或文件夹，如果是文件夹会递归将其下所有 XML 都进行转换
# 默认是当前目录下所有的 XML 文件
xml_file_or_path = "."

# 输出的 ASS 文件，默认为输入文件名将 .xml 替换为 .ass，如果输入是文件夹则忽略
# ass_file = "out.ass"

# 弹幕时间轴偏移，>0 会让弹幕延后，<0 会让弹幕提前，单位为秒
time_offset = 0.0

# 渲染的屏幕分辨率，这个并不会影响渲染区域的大小，只是字体的相对大小，可以不用改动
width = 1280
height = 720

# 使用字体名称
font = "黑体"

# 弹幕字体大小
font_size = 25

# 下面两个数值用来计算弹幕的【水平距离】
# width_ratio 是一个比例数，用来计算平衡不同字体的宽度。
#   有的字体比较粗、比较宽，可以适当调大 width_ratio（如 1.4、1.6），
#   有的字体比较细、比较窄，可以适当调小 width_ratio（如 1.0、1.2）。
# horizontal_gap 用来调整弹幕时间的水平距离，单位是像素，如果想拉开弹幕之间的距离，可以调大 horizontal_gap
width_ratio = 1.2
horizontal_gap = 20.0

# 计算弹幕高度的数值，即【行高度/行间距】。数值越大，弹幕的垂直距离越大
lane_size = 32

# 弹幕在屏幕上的【持续时间】，单位为秒，可以有小数
duration = 15

# 【正常弹幕的屏幕填充占比】，默认为 50%，即“半屏填充”。
float_percentage = 0.5

# 弹幕的不透明度，越小越透明，越大越不透明
alpha = 0.7

# 默认会跳过 ass 比 xml 修改时间更晚的文件，修改此参数为 true 会强制转换
force = false

# 黑名单，需要过滤的关键词列表文件，每行一个关键词
# denylist = "黑名单.txt"

# 在处理完后暂停等待输入
pause = true

# 弹幕的描边宽度，单位为像素
outline = 0.8

# 字体是否加粗
bold = false
