# 在本文件存在时，优先读取本文件的内容，不会读取命令行参数


# 需要转换的 XML 文件或文件夹，如果是文件夹会递归将其下所有 XML 都进行转换
# 默认是当前目录
xml_file_or_path = "."

# 输出的 ASS 文件，默认为输入文件名将 .xml 替换为 .ass，如果输入是文件夹则忽略
# ass_file = "out.ass"

# 屏幕宽度
width = 1280

# 屏幕高度
height = 720

# 使用字体
font = "黑体"

# 弹幕字体大小
font_size = 25

# 为避免重叠需要调大这个数值，即“水平间距”
# 数值越大，弹幕的水平间距越大
width_ratio = 1.2

# 计算弹幕高度的数值，即“行高度/行间距”
# 数值越大，弹幕的垂直距离越大
lane_size = 32

# 弹幕在屏幕上的持续时间，单位为秒，可以有小数
duration = 15

# 屏幕上滚动弹幕最多高度百分比，默认为 50%
float_percentage = 0.5

# 弹幕的不透明度，越小越透明，越大越不透明
alpha = 0.7

# 默认会跳过 ass 比 xml 修改时间更晚的文件，此参数会强制转换
force = false

# 黑名单，需要过滤的关键词列表文件，每行一个关键词
# denylist = "黑名单.txt"

# 在处理完后暂停等待输入
pause = true
